"""added new field to create recipe

Revision ID: 2bb8ca8d9ad2
Revises: 047ab7cc0f09
Create Date: 2020-01-12 11:11:37.908649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb8ca8d9ad2'
down_revision = '047ab7cc0f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('cook_method', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'cook_method')
    # ### end Alembic commands ###
