"""add column

Revision ID: 8ccab9113666
Revises: 7fe347bcebce
Create Date: 2020-01-12 15:04:12.910950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ccab9113666'
down_revision = '7fe347bcebce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('cook_method', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'cook_method')
    # ### end Alembic commands ###
