"""empty message

Revision ID: 9d6ebf51c9bf
Revises: 2f177052f913
Create Date: 2020-01-12 20:13:20.112825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6ebf51c9bf'
down_revision = '2f177052f913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('cook_method', sa.Text(), nullable=True))
    op.add_column('recipe', sa.Column('ingredients', sa.Text(), nullable=True))
    op.add_column('recipe', sa.Column('recipe_image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'recipe_image')
    op.drop_column('recipe', 'ingredients')
    op.drop_column('recipe', 'cook_method')
    # ### end Alembic commands ###
